# Generated by Django 6.0.1 on 2026-02-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentqr',
            options={'ordering': ['package_amount'], 'verbose_name': 'Payment QR Code', 'verbose_name_plural': 'Payment QR Codes'},
        ),
        migrations.AddField(
            model_name='paymentqr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentqr',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentqr',
            name='package_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Package amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentqr',
            name='package_name',
            field=models.CharField(default='Default Package', help_text="Package name like '60 UC BGMI', '300 UC BGMI', etc.", max_length=200),
        ),
    ]
